apiVersion: v1
kind: Service
metadata:
  name: techlogix-inventory-service
spec:
  selector:
    app: techlogix-inventory
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080